spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/coffee_shop
    password: 123456
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  data:
    web:
      pageable:
        one-indexed-parameters: true
debug: true
springdoc:
  default-produces-media-type: application/json

