name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
permissions:
  contents: read
concurrency:
  group: ci-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true
jobs:
  build-project:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    - name: Gradle build
      working-directory: projects
      run: ./gradlew build -Pcoverage
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      env:
         CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
     
